### ISSUE TITLE
Set up ContainerSSH metrics server with Prometheus

### ISSUE THREAD

**Issue by paseaf** [paseaf/ContainerSSH-honeypot#45]
We need to set up
```
metrics:
  enable: true
  listen: "0.0.0.0:9101"
  path: "/metrics"
```
in our containerssh config to get containerssh metrics.

https://containerssh.io/reference/metrics/
- is country identification possible?
- update architecture diagram with added metrics server
